name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout cppcheck sources
        uses: actions/checkout@v4
        with:
          repository: 'danmar/cppcheck'
          ref: '2.13.4'
          path: src/cppcheck

      - name: Build and install cppcheck
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          sudo cmake --install .
        working-directory: src/cppcheck

      - name: Execute linter check with cppcheck
        run: |
          set -x
          cppcheck --enable=all --inline-suppr --template='{file}:{line},{severity},{id},{message}' --error-exitcode=1 --suppress=missingIncludeSystem --suppress=missingInclude --suppress=unmatchedSuppression:pg_stat_monitor.c --check-config .

