name: PGXN
on:
  workflow_dispatch:
  pull_request:

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          path: src/pg_stat_monitor

      - name: Install PGXN Client
        run: pip install pgxnclient
      
      - name: Install PGXN Utils
        run: sudo pgxn install pgxn_utils

      - name: Install PGXN meta validator
        run: sudo cpan PGXN::Meta::Validator
