name: PGXN
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    container: pgxn/pgxn-tools
    steps:
    - name: Validate version tag
      run: '[[ ${{ inputs.version }} =~ ^[0-9]+.[0-9]+.[0-9]+ ]]'
    - name: Check out
      uses: actions/checkout@v4
      with:
        ref: '${{ inputs.version }}'
    - name: Bundle
      id: bundle
      run: pgxn-bundle
    # - name: Upload
    #   env:
    #     PGXN_USERNAME: percona
    #     PGXN_PASSWORD: ${{ secrets.PGXN_PERCONA }}
    #   run: pgxn-release
